/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BrowseImport } from './routes/browse'
import { Route as IndexImport } from './routes/index'
import { Route as CollectionsIndexImport } from './routes/collections/index'
import { Route as CollectionsCollectionSlugImport } from './routes/collections/$collectionSlug'

// Create/Update Routes

const BrowseRoute = BrowseImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsIndexRoute = CollectionsIndexImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionsCollectionSlugRoute = CollectionsCollectionSlugImport.update({
  id: '/collections/$collectionSlug',
  path: '/collections/$collectionSlug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseImport
      parentRoute: typeof rootRoute
    }
    '/collections/$collectionSlug': {
      id: '/collections/$collectionSlug'
      path: '/collections/$collectionSlug'
      fullPath: '/collections/$collectionSlug'
      preLoaderRoute: typeof CollectionsCollectionSlugImport
      parentRoute: typeof rootRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/collections/$collectionSlug': typeof CollectionsCollectionSlugRoute
  '/collections': typeof CollectionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/collections/$collectionSlug': typeof CollectionsCollectionSlugRoute
  '/collections': typeof CollectionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/collections/$collectionSlug': typeof CollectionsCollectionSlugRoute
  '/collections/': typeof CollectionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/browse' | '/collections/$collectionSlug' | '/collections'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/browse' | '/collections/$collectionSlug' | '/collections'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/collections/$collectionSlug'
    | '/collections/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CollectionsCollectionSlugRoute: typeof CollectionsCollectionSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CollectionsCollectionSlugRoute: CollectionsCollectionSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/browse",
        "/collections/$collectionSlug",
        "/collections/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/browse": {
      "filePath": "browse.tsx"
    },
    "/collections/$collectionSlug": {
      "filePath": "collections/$collectionSlug.tsx"
    },
    "/collections/": {
      "filePath": "collections/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
